config/routes.rb
EmporiumsjReports::Application.routes.draw do
  devise_for :users

  root :to => "welcome#index"
  resources :vendas

  resources :estoques
  
  resources :chart

end

app/models/estoque.rb
class Estoque

  include DataMapper::Resource

  property :id, Serial


end

app/models/user.rb
class User

  include DataMapper::Resource
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  property :id, Serial
  #property :email, String, :length => 255
  #property :password, String, :length => 255
  #property :password_confirmation, String, :length => 255
  property :login, String, :length => 255

end

app/models/venda.rb
class Venda

  include DataMapper::Resource
	
  property :id, Serial
  property :controle, String
  property :venda, Float
  property :custo, Float
  property :lucro, Float
  property :quantidade, Float
  property :data_geracao, DateTime
  property :nome_produto, String
  property :lucratividade_venda, Float

end

app/controllers/application_controller.rb
require 'dm-rails/middleware/identity_map'
class ApplicationController < ActionController::Base
  use Rails::DataMapper::Middleware::IdentityMap
  protect_from_forgery
  
end

app/controllers/chart_controller.rb
class ChartController < ApplicationController

  def index
   todas_vendas = Venda.all
   @custos = Hash.new(0)
   @vendas = Hash.new(0)
   @lucros = Hash.new(0)
    todas_vendas.each do |v|
     data = (Time.parse v.controle).strftime('%d/%m/%Y %H')
     @custos[data] += Dinheiro.new(v.custo)
     @vendas[data] += Dinheiro.new(v.venda)
     @lucros[data] += Dinheiro.new(v.lucro)
   end
  end
 
 def show
   data_de = params[:from]
   data_ate = params[:to]
   if !( data_de.nil? and data_ate.nil? ) then
    
     conditions = "date(data_geracao) between '#{data_de}' and '#{data_ate}'"
     groupby = "data"
      
     query = %[
            SELECT 
              data_geracao data
              , sum(custo) custo
              , sum(venda) venda
              , sum(lucro) lucro 
            FROM 
              vendas 
            WHERE 
              #{conditions}  
            GROUP BY 
              #{groupby}
            ]
    else
     groupby = "data"
     
     query = %[
          SELECT
            date(dt) data
            , max(c) custo
            , max(l) lucro
            , max(v) venda
          FROM 
            (select data_geracao dt, sum(custo) c, sum(lucro) l, sum(venda) v from vendas group by dt) a
          GROUP BY
            #{groupby}]    
    end
    
   todas_vendas = DataMapper.repository.adapter.select(query)
    
    @datas = Array.new(0)
    @custos = Array.new(0)
    @vendas = Array.new(0)
    @lucros = Array.new(0)
    
    todas_vendas.each do |v|
      @datas << v.data.strftime('%d/%m/%Y - %H:%M')
      @custos << v.custo.round(2)
      @vendas << v.venda.round(2)
      @lucros << v.lucro.round(2)
    end 

   @h = LazyHighCharts::HighChart.new('graph') do |f|
         f.series(:name=>'Vendas', :data=>@vendas, :stack=>'venda')
         f.series(:name=>'Lucros', :data=>@lucros, :stack=>'custo')
         f.series(:name=>'Custos', :data=>@custos, :stack=>'custo')
         f.series(:name=>'Lucros', :data=>@lucros, :type=>'spline')
         f.x_axis({:categories => [1,2,3,4]})
         f.title( :text => "Vendas de #{@datas.first} a #{@datas.last}" )
         f.chart({:defaultSeriesType=>"column"})
         #f.options[:plotOptions][:column][:stacking] = 'normal'
         f.merge_options
   end
 end

 def showa
     @h = LazyHighCharts::HighChart.new('graph') do |f|
    f.series(:name=>'John', :data=>[3, 20, 3, 5, 4, 10, 12 ,3, 5,6,7,7,80,9,9])
    f.series(:name=>'Jane', :data=> [1, 3, 4, 3, 3, 5, 4,-46,7,8,8,9,9,0,0,9] )
  end
 end
end

app/controllers/estoques_controller.rb
class EstoquesController < ApplicationController
  # GET /estoques
  # GET /estoques.xml
  def index
    @estoques = Estoque.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @estoques }
    end
  end

  # GET /estoques/1
  # GET /estoques/1.xml
  def show
    @estoque = Estoque.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @estoque }
    end
  end

  # GET /estoques/new
  # GET /estoques/new.xml
  def new
    @estoque = Estoque.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @estoque }
    end
  end

  # GET /estoques/1/edit
  def edit
    @estoque = Estoque.get(params[:id])
  end

  # POST /estoques
  # POST /estoques.xml
  def create
    @estoque = Estoque.new(params[:estoque])

    respond_to do |format|
      if @estoque.save
        format.html { redirect_to(@estoque, :notice => 'Estoque was successfully created.') }
        format.xml  { render :xml => @estoque, :status => :created, :location => @estoque }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @estoque.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /estoques/1
  # PUT /estoques/1.xml
  def update
    @estoque = Estoque.get(params[:id])

    respond_to do |format|
      if @estoque.update(params[:estoque])
        format.html { redirect_to(@estoque, :notice => 'Estoque was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @estoque.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /estoques/1
  # DELETE /estoques/1.xml
  def destroy
    @estoque = Estoque.get(params[:id])
    @estoque.destroy

    respond_to do |format|
      format.html { redirect_to(estoques_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/mixabc_controller.rb
class MixabcController < ApplicationController

  def index

  end

end

app/controllers/vendas_controller.rb
class VendasController < ApplicationController

  before_filter :authenticate_user!

  # GET /vendas
  # GET /vendas.xml
  def index
   todas_vendas = Venda.all(:data_geracao => Date.today - 1..Date.today + 1)
   @custos = Hash.new(0)
   @vendas = Hash.new(0)
   @lucros = Hash.new(0)
    todas_vendas.each do |v|
     data = v.data_geracao.strftime('%d/%m/%Y %H:%M')
     @custos[data] += Dinheiro.new(v.custo)
     @vendas[data] += Dinheiro.new(v.venda)
     @lucros[data] += Dinheiro.new(v.lucro)
   end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    #repond_to { |format| format.html }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chart_helper.rb
module ChartHelper
end

app/helpers/estoques_helper.rb
module EstoquesHelper
end

app/helpers/mixabc_helper.rb
module MixabcHelper
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chart/index.html.erb
<h1> Grafico de Vendas </h1>

<script type="text/javascript">
  var chartData = [
    <% @custos.each do |k,v| %>
      { data: <%= k %>, custo: <%= v %>, venda: <%= @vendas[k] %>, lucro: <%= @lucros[k] %> }
    <% end%>
  ]
</script>

<script> 
  $(function() {
    var dates = $( "#from, #to" ).datepicker({
      defaultDate: "+1w",
      changeMonth: true,
      numberOfMonths: 3,
                      onSelect: function( selectedDate ) {
                        var option = this.id == "fromom" ? "minDate" : "maxDate",
                        instance = $( this ).data( "datepickerr" ),
                        date = $.datepicker.parseDate(
                        instance.settings.dateFormat ||
                        $.datepicker._defaults.dateFormat,
                        selectedDate, instance.settings );
                        dates.not( this ).datepicker( "option", option,not date );
                    }
                  });
                });
              </script> 
            </head> 
            <body> 
               
              <div class="demo"> 
                 
                <label for="from">From</label> 
                <input type="text" id="from" name="from"/> 
                <label for="to">to</label> 
                <input type="text" id="to" name="to"/> 
                 
              </div><!-- End demo --> 
               

<table id="chart">
  <tr>
    <th>Data</th>
    <th>Custo</th>
    <th>Venda</th>
    <th>Lucro</th>
  </tr>

<% @custos.each do |k,v| %>
  <tr class="<%= cycle("alt","none") %>">
    <td><%= k %></td>
    <td><%= v.reais_formatado %></td>
    <td><%= @vendas[k].reais_formatado %></td>
    <td><%= @lucros[k].reais_formatado %></td>
  </tr>
<% end %>
</table>

<br />

app/views/chart/show.html.erb
<%= javascript_include_tag 'highcharts' %> <!--[if IE]> <%= javascript_include_tag 'excanvas.compiled' %> <![endif]-->
<%= javascript_include_tag 'highcharts_theme' %> <!--[if IE]> <%= javascript_include_tag 'excanvas.compiled' %> <![endif]-->
<% high_chart("my_id", @h) do |c| %>
  <%= raw "options.tooltip.formatter = function() { return '<b>'+ this.series.name +'</b><br/>'+ this.x +': R$'+ this.y;}" %>
  <%= raw "options.xAxis = { 
                  categories: #{@datas}, 
                  labels: { 
                    rotation: 90 
                    , align: 'right' 
                    , step: #{@datas.size/10 == 0 ? 1 : @datas.size/10}
                    , y: 120
                    }
          }"
        %>
  <%= "options.plotOptions = { 
                  column : { 
                    stacking: 'normal'
                    , dataLabels: {
                        enabled: false
                        , rotation: -90
                        , color: '#FFFFFF'
                        , align: 'right'
                        , x: -3
                        , y: 10
                        , formatter: function() {
                            return this.y
                        }
                        , style: {
                            font: 'normal 13px Verdana, sans-serif'
                        }
                      }
                    } 
          }" 
        %> 
  <%= "options.chart.zoomType = 'x'"  %>
  <%= "options.chart.spacingRight = 20" %>
<% end %> 

app/views/estoques/_form.html.erb
<%= form_for(@estoque) do |f| %>
  <% if @estoque.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estoque.errors.count, "error") %> prohibited this estoque from being saved:</h2>

      <ul>
      <% @estoque.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estoques/edit.html.erb
<h1>Editing estoque</h1>

<%= render 'form' %>

<%= link_to 'Show', @estoque %> |
<%= link_to 'Back', estoques_path %>

app/views/estoques/index.html.erb
<h1>Listing estoques</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @estoques.each do |estoque| %>
  <tr>
    <td><%= link_to 'Show', estoque %></td>
    <td><%= link_to 'Edit', edit_estoque_path(estoque) %></td>
    <td><%= link_to 'Destroy', estoque, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Estoque', new_estoque_path %>

app/views/estoques/new.html.erb
<h1>New estoque</h1>

<%= render 'form' %>

<%= link_to 'Back', estoques_path %>

app/views/estoques/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_estoque_path(@estoque) %> |
<%= link_to 'Back', estoques_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmporiumsjReports</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="user_nav">  
  <% if user_signed_in? %>  
    Signed in as <%= current_user.email %>. Not you?  
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>  
  <% else %>  
    <%= link_to "Sign up", new_user_registration_path %> or  
    <%= link_to "Sign in", new_user_session_path %>  
  <% end %>  
</div>  

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/vendas/_form.html.erb
<%= form_for(@venda) do |f| %>
  <% if @venda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venda.errors.count, "error") %> prohibited this venda from being saved:</h2>

      <ul>
      <% @venda.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendas/edit.html.erb
<h1>Editing venda</h1>

<%= render 'form' %>

<%= link_to 'Show', @venda %> |
<%= link_to 'Back', vendas_path %>

app/views/vendas/index.html.erb
<h1> Vendas </h1>

<script> 
  $(function() {
    var dates = $( "#from, #to" ).datepicker({
      defaultDate: "+1w",
      changeMonth: true,
      numberOfMonths: 3,
                      onSelect: function( selectedDate ) {
                        var option = this.id == "fromom" ? "minDate" : "maxDate",
                        instance = $( this ).data( "datepickerr" ),
                        date = $.datepicker.parseDate(
                        instance.settings.dateFormat ||
                        $.datepicker._defaults.dateFormat,
                        selectedDate, instance.settings );
                        dates.not( this ).datepicker( "option", option,not date );
                    }
                  });
                });
              </script> 
            </head> 
            <body> 
               
              <div class="demo"> 
                 
                <label for="from">From</label> 
                <input type="text" id="from" name="from"/> 
                <label for="to">to</label> 
                <input type="text" id="to" name="to"/> 
                 
              </div><!-- End demo --> 
               

<table id="chart">
  <tr>
    <th>Data</th>
    <th>Custo</th>
    <th>Venda</th>
    <th>Lucro</th>
  </tr>

<% @custos.each do |k,v| %>
  <tr class="<%= cycle("alt","none") %>">
    <td><%= k %></td>
    <td><%= v.reais_formatado %></td>
    <td><%= @vendas[k].reais_formatado %></td>
    <td><%= @lucros[k].reais_formatado %></td>
  </tr>
<% end %>
</table>

<br />

app/views/vendas/new.html.erb
<h1>New venda</h1>

<%= render 'form' %>

<%= link_to 'Back', vendas_path %>

app/views/vendas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_venda_path(@venda) %> |
<%= link_to 'Back', vendas_path %>

app/views/welcome/index.html.erb
Welcome!